# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ haskellPackages ? (import <nixpkgs> {}).haskellPackages }:

haskellPackages.cabal.mkDerivation (self: {
  pname = "stellar-haskell";
  version = "0.1.0.0";
  sha256 = "0";
  src = "./src";
  isLibrary = true;
  buildDepends = with haskellPackages; [
    aeson HUnit lens lensFamilyCore lensFamilyTh QuickCheck text wreq
  ];
  testDepends = with haskellPackages; [ aeson hspec lens QuickCheck text ];
  meta = {
    description = "Stellar API for Haskell";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
  buildTools = with haskellPackages; [ cabalInstall ];
})
